version: '3.8'
services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
#    volumes:
#      - cache:/data

  redis-insight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - "5540:5540"

#volumes:
#  cache:
#    driver: local